name: push image to gcp
on: push
jobs:
  build-push-gcr:
    name: build and push to gcp
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: myapp
      PROJECT_ID: interns
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker client
        run: gcloud auth configure-docker --quiet

      - name: Push Docker image to GCR
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest