name: learn-githubactions
run-name: ${{ github.actor }} is learning github actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.315.0
      - uses: actions/setup-node@v2.315.0
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v